version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ../mylog/debug/debug.log
    backupCount: 500
    maxBytes: 10485760
    encoding: utf8
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../mylog/info.log
    backupCount: 50
    maxBytes: 10485760
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ../mylog/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: yes
  tou:
    level: DEBUG
    handlers: [info_file_handler, debug_file_handler, console]
    propagate: yes
  wei:
    level: DEBUG
    handlers: [info_file_handler, debug_file_handler]
    propagate: yes
root:
  level: DEBUG
  handlers: [console_err, error_file_handler]